/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarydemo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseph
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
        populateTable("","");
    }
    
    public void populateTable(String searchType, String searchKey){
         try {
            MyConnection cc = new MyConnection();
            Connection con = DriverManager.getConnection(cc.getConnection() + cc.getDatabase(),
                    cc.getDatabaseUsername(),
                    cc.getDatabasePassword());
            Statement st = con.createStatement();
            String sql = "Select b.id as transactionnumber, bb.id_book as \"book id\", b.title, \n" +
                        "u.name as borrower, \n" +
                        "bb.dateTimeBorrowed, bb.remarks\n" +
                        " from books as b \n" +
                        "inner join borrowbook as bb on b.id = bb.id_book\n" +
                        "inner join users as u on u.id = bb.id_user";
            if (searchType.equals("borrower") && (!searchKey.equals(""))){
                sql = sql + " where u.name like '%"+searchKey+"%'";
            } else if(searchType.equals("book") && (!searchKey.equals(""))) {
                sql = sql + " where b.title like '%"+searchKey+"%'";
            }
            ResultSet rs = st.executeQuery(sql);

            //Retrieving the ResultSetMetadata object
            ResultSetMetaData rsMetaData = rs.getMetaData();
            //Retrieving the list of column names
            int count = rsMetaData.getColumnCount();

            DefaultTableModel model = new DefaultTableModel();
            jTblBorrower.setModel(model);
            //recreate the columns
            for (int i = 1; i <= count; i++) {
                model.addColumn(rsMetaData.getColumnLabel(i));
            }
            //retrieve the records and display to table
            while (rs.next()) {
                String[] record = new String[count];
                for (int i = 0; i < count; i++) {
                    record[i] = rs.getString(i + 1);
                }
                //cache.add(record);
                model.addRow(record);
            }

            rs.close();
            st.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTxtSearch = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jBtnReturnBook = new javax.swing.JButton();
        jRdoBook = new javax.swing.JRadioButton();
        jRdoBorrower = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBorrower = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Enter search keyword");

        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jBtnReturnBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnReturnBook.setText("Return Book");
        jBtnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReturnBookActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdoBook);
        jRdoBook.setText("Book title");

        buttonGroup1.add(jRdoBorrower);
        jRdoBorrower.setSelected(true);
        jRdoBorrower.setText("Borrower name");

        jTblBorrower.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "A", "B", "Title 3", "Title 4"
            }
        ));
        jTblBorrower.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTblBorrower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblBorrowerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblBorrower);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jRdoBorrower)
                .addGap(18, 18, 18)
                .addComponent(jRdoBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnReturnBook)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addComponent(jTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnSearch)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdoBook)
                    .addComponent(jRdoBorrower))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnReturnBook)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnSearch))
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        // TODO add your handling code here:
        if(jRdoBorrower.isSelected()){
            populateTable("borrower",jTxtSearch.getText());    
        }else if(jRdoBook.isSelected()){
            populateTable("book",jTxtSearch.getText());
        }
        
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jTblBorrowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBorrowerMouseClicked
        // TODO add your handling code here:
        int row = jTblBorrower.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTblBorrower.getModel();

    }//GEN-LAST:event_jTblBorrowerMouseClicked

    private void jBtnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReturnBookActionPerformed
        // TODO add your handling code here:
//        String msg = borrowerName + " is about to borrow book " + jBookTitle.getText() + "?";
//        int result = JOptionPane.showConfirmDialog(this, msg, "Borrow Book",
//            JOptionPane.YES_NO_OPTION,
//            JOptionPane.QUESTION_MESSAGE);
//        if (result == JOptionPane.YES_OPTION) {
//            //insert to borrow table
//            String sql = "Insert into borrowbook(id_book,id_user,dateTimeBorrowed,status,remarks) values (?,?,?,?,?)";
//            try {
//                MyConnection cc = new MyConnection();
//                Connection con = DriverManager.getConnection(cc.getConnection() + cc.getDatabase(),
//                    cc.getDatabaseUsername(),
//                    cc.getDatabasePassword());
//                PreparedStatement pst = con.prepareStatement(sql);
//                //get the selected author
//
//                pst.setInt(1, Integer.parseInt(jBookID.getText()));
//                pst.setInt(2, borrowerId);
//                pst.setString(3, LocalDate.now().toString());
//                pst.setString(4, "borrowed");
//                pst.setString(5, "NA");
//
//                int row = pst.executeUpdate();
//                //call the populateTable to refresh the content
//                if (row > 0) {
//                    //update the status of the book borrowed
//                    String bSql = "Update books set borrowed = 'yes' where id=" + jBookID.getText();
//                    PreparedStatement pst2 = con.prepareStatement(bSql);
//
//                    int bRow = pst2.executeUpdate();
//                    if (bRow > 0) {
//                        JOptionPane.showMessageDialog(rootPane, "Book has been borrowed!");
//                        this.setVisible(false);
//                    }
//                }
//                pst.close();
//                con.close();
//
//            } catch (SQLException e) {
//                e.printStackTrace();
//            }
//            //display thank you message
//        }
    }//GEN-LAST:event_jBtnReturnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnReturnBook;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRdoBook;
    private javax.swing.JRadioButton jRdoBorrower;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblBorrower;
    private javax.swing.JTextField jTxtSearch;
    // End of variables declaration//GEN-END:variables
}
